"""The catalogues this package owns exist again in rubasace/sidevoice `packages/browser-audio`, copied there
for the page's build: the voice catalogue as `catalog.json` (which the page's Kokoro reads), the model
catalogue and its resolver vectors as `models.json` and `models.vectors.json` (generated by that package's
`copy-core-catalogs.mjs`, never edited by hand). This is the one place that says whether the copies still
agree (it runs when SIDEVOICE_REPOSITORY names a checkout, and skips otherwise)."""
import json
import os
import unittest
from importlib.resources import files
from pathlib import Path

COPIES = {('pipeline', 'catalog.json'): 'catalog.json',
          ('models', 'catalog.json'): 'models.json',
          ('models', 'vectors.json'): 'models.vectors.json'}


class CatalogContractTest(unittest.TestCase):
    def test_the_core_and_the_page_know_the_same_catalogues(self):
        page = Path(os.environ.get('SIDEVOICE_REPOSITORY') or '/nonexistent') / 'packages' / 'browser-audio'
        if not (page / 'catalog.json').exists():
            self.skipTest('SIDEVOICE_REPOSITORY does not name a rubasace/sidevoice checkout')
        for (package, name), copy in COPIES.items():
            with self.subTest(copy=copy):
                core = json.loads(files(f'sidevoice_core.{package}').joinpath(name).read_text(encoding='utf8'))
                self.assertEqual(core, json.loads((page / copy).read_text(encoding='utf8')))
