"""The catalogues this package owns exist again in the sidevoice-web repository's `packages/browser-audio`, copied there
for the page's build: the voice catalogue as `catalog.json` (which the page's Kokoro reads), the model
catalogue and its resolver vectors as `models.json` and `models.vectors.json` (generated by that package's
`copy-core-catalogs.mjs`, never edited by hand), and the model checks' clips and phrases (`models/checks/`) as
`checks/`, byte for byte. This is the one place that says whether the copies still
agree (it runs when SIDEVOICE_REPOSITORY names a sidevoice-web checkout, and skips otherwise)."""
import json
import os
import unittest
from importlib.resources import files
from pathlib import Path

COPIES = {('pipeline', 'catalog.json'): 'catalog.json',
          ('models', 'catalog.json'): 'models.json',
          ('models', 'vectors.json'): 'models.vectors.json'}


class CatalogContractTest(unittest.TestCase):
    def test_the_core_and_the_page_know_the_same_catalogues(self):
        page = Path(os.environ.get('SIDEVOICE_REPOSITORY') or '/nonexistent') / 'packages' / 'browser-audio'
        if not (page / 'catalog.json').exists():
            self.skipTest('SIDEVOICE_REPOSITORY does not name a sidevoice-web checkout')
        for (package, name), copy in COPIES.items():
            with self.subTest(copy=copy):
                core = json.loads(files(f'sidevoice_core.{package}').joinpath(name).read_text(encoding='utf8'))
                self.assertEqual(core, json.loads((page / copy).read_text(encoding='utf8')))
        checks = files('sidevoice_core.models').joinpath('checks')
        names = sorted(entry.name for entry in checks.iterdir())
        self.assertEqual(names, sorted(entry.name for entry in (page / 'checks').iterdir()))
        for name in names:
            with self.subTest(check=name):
                self.assertEqual(checks.joinpath(name).read_bytes(), (page / 'checks' / name).read_bytes())
