// Generated by tools/contract_slice.py from contracts/core-slice.openapi.json.
// These two routes have one operation source; the remaining router is outside this slice.
use super::*;

#[async_trait::async_trait]
pub(super) trait ContractSliceHandlers: Send + Sync + 'static {
    async fn get_presentation_languages() -> Response;
    async fn post_transcription_trial(
        state: State<Arc<AppState>>,
        device: Extension<AuthenticatedDevice>,
        headers: HeaderMap,
        body: axum::body::Bytes,
    ) -> Response;
}

pub(super) fn routes<H: ContractSliceHandlers>() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/presentation/languages", get(H::get_presentation_languages))
        .route("/api/models/transcription/preview", post(H::post_transcription_trial))
}
