#!/usr/bin/env python3
"""Emit the two required Core handlers and Axum routes from one OpenAPI 3.1 slice."""

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts/core-slice.openapi.json"
RUST = ROOT / "rust/server/contract_slice_generated.rs"
SCHEMA = ROOT / "contracts/generated/core-types.schema.json"

# Extraction signatures preserve the accepted handlers' raw-body and refusal policy.
SIGNATURES = {
    "getPresentationLanguages": "",
    "postTranscriptionTrial": (
        "state: State<Arc<AppState>>,\n"
        "        device: Extension<AuthenticatedDevice>,\n"
        "        headers: HeaderMap,\n"
        "        body: axum::body::Bytes,"
    ),
}


def operations(source):
    found = []
    if source.get("openapi") != "3.1.0" or source.get("jsonSchemaDialect") != "https://json-schema.org/draft/2020-12/schema":
        raise ValueError("the slice requires OpenAPI 3.1 and JSON Schema draft 2020-12")
    for path, methods in source["paths"].items():
        for method, operation in methods.items():
            name = operation["operationId"]
            if method not in {"get", "post"} or name not in SIGNATURES:
                raise ValueError(f"unsupported operation: {method} {path} ({name})")
            if operation.get("security") != [{"deviceBearer": []}]:
                raise ValueError(f"missing bearer class: {name}")
            found.append((name, method, path))
    if {name for name, _, _ in found} != set(SIGNATURES) or len(found) != len(SIGNATURES):
        raise ValueError("the two required operations must appear exactly once")
    return sorted(found)


def rust_source(found):
    methods = []
    routes = []
    for name, method, path in found:
        rust_name = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
        signature = SIGNATURES[name]
        args = f"\n        {signature}\n    " if signature else ""
        methods.append(f"    async fn {rust_name}({args}) -> Response;")
        routes.append(f'        .route("{path}", {method}(H::{rust_name}))')
    return (
        "// Generated by tools/contract_slice.py from contracts/core-slice.openapi.json.\n"
        "// These two routes have one operation source; the remaining router is outside this slice.\n"
        "use super::*;\n\n"
        "#[async_trait::async_trait]\n"
        "pub(super) trait ContractSliceHandlers: Send + Sync + 'static {\n"
        + "\n".join(methods)
        + "\n}\n\n"
        "pub(super) fn routes<H: ContractSliceHandlers>() -> Router<Arc<AppState>> {\n"
        "    Router::new()\n"
        + "\n".join(routes)
        + "\n}\n"
    )


def schema_source(source):
    definitions = json.loads(json.dumps(source["components"]["schemas"]))
    for schema in definitions.values():
        rewrite_refs(schema)
    properties = {
        name[0].lower() + name[1:]: {"$ref": f"#/$defs/{name}"}
        for name in definitions
        if name in {"LanguagesResponse", "TrialRequest", "TrialResponse", "TrialRefusal", "VoiceMediaCommand"}
    }
    result = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "CoreContractSlice",
        "type": "object",
        "required": list(properties),
        "properties": properties,
        "$defs": definitions,
    }
    return json.dumps(result, indent=2, ensure_ascii=False) + "\n"


def rewrite_refs(value):
    if isinstance(value, dict):
        for key, child in value.items():
            if key == "$ref":
                if not child.startswith("#/components/schemas/"):
                    raise ValueError(f"unsupported schema reference: {child}")
                value[key] = child.replace("#/components/schemas/", "#/$defs/")
            else:
                rewrite_refs(child)
    elif isinstance(value, list):
        for child in value:
            rewrite_refs(child)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "check"))
    args = parser.parse_args()
    source = json.loads(SOURCE.read_text())
    found = operations(source)
    generated = {RUST: rust_source(found), SCHEMA: schema_source(source)}
    server = (ROOT / "rust/server.rs").read_text()
    for _, _, path in found:
        if re.search(r'\.route\s*\(\s*"' + re.escape(path) + r'"', server):
            raise ValueError(f"manual duplicate of generated route: {path}")
    if args.command == "generate":
        for path, contents in generated.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
    else:
        for path, contents in generated.items():
            if not path.exists() or path.read_text() != contents:
                raise ValueError(f"generated output differs: {path.relative_to(ROOT)}")
    print(f"contract slice {args.command}: {len(found)} generated HTTP operations")


if __name__ == "__main__":
    try:
        main()
    except (KeyError, ValueError) as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error
